#!/usr/bin/env node
// Kura CLI.
//   kura index [--model Xenova/bge-m3]
//     Build the search index + precompiled MDX for the current Kura docs app and FREEZE both
//     as importable modules (app/_index.ts, app/_mdx.ts) — so the worker bundle imports them
//     and never reads the filesystem (Workers-safe; mirrors June's app/_content.ts freeze).
//     A content hash short-circuits re-embedding when nothing changed (cheap to run pre-dev).
import { buildIndex } from "@kurajs/docs/search";
import { docsRoute, pruneStaleDocsRoutes } from "./routes.js";
import { loadCliConfig } from "./config-load.js";
import { collectMeta, collectLastUpdated, discoverLocales } from "./content-walk.js";
import { repoRootOf, detectRepo, gitOriginUrl, linkRef, sourceMapOf, repoPathMapper, collectSourcePaths, gitTrackedFiles, collectRepoTargets, renderLinksTs } from "./links-freeze.js";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawn } from "node:child_process";
import { pathToFileURL, fileURLToPath } from "node:url";

function arg(name: string, def?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
}

async function cmdIndex(): Promise<void> {
  const cwd = process.cwd();
  const contentPath = path.join(cwd, "app", "_content.ts");
  if (!fs.existsSync(contentPath)) {
    console.error("kura index: app/_content.ts not found — run `june gen` first (in a Kura docs app).");
    process.exit(1);
  }
  const model = arg("model", "Xenova/bge-m3")!;
  const indexTs = path.join(cwd, "app", "_index.ts");
  const mdxTs = path.join(cwd, "app", "_mdx.ts");
  const metaTs = path.join(cwd, "app", "_meta.ts");

  // Read config from kura.toml (real parse) or kura.config.ts (text-scanned — `kura index` never
  // executes user code). Both collapse to the same shape; see config-load.ts.
  const cfg = loadCliConfig(cwd);
  // Docs-as-code sources (`content.sources`): June already merged their ENTRIES into app/_content.ts
  // at `june gen`; here they extend Kura's own walks — meta.json nav, lastUpdated dates, locale
  // discovery — over the same external trees.
  const contentSources = cfg.contentSources;
  // Locale buckets are DECLARED (config i18n: defaultLocale + locales keys), never guessed by folder
  // shape. No i18n ⇒ no locales.
  const declaredLocales = new Set(cfg.locales);

  // Nav metadata (meta.json) — validated and frozen first, so a bad meta fails fast and cheap.
  // META is the default tree; META_LOCALES holds each locale mirror's per-folder overrides.
  const { meta, metaLocales, errors: metaErrors } = collectMeta(cwd, contentSources, declaredLocales);
  if (metaErrors.length) {
    console.error("kura index: meta.json validation failed —\n  " + metaErrors.join("\n  "));
    process.exit(1);
  }
  fs.mkdirSync(path.dirname(metaTs), { recursive: true });
  const metaContents =
    "// AUTO-GENERATED by `kura index` — do not edit. Frozen folder nav metadata (from meta.json).\n" +
    `export const META = ${JSON.stringify(meta)} as const;\n` +
    "// Per-locale overrides (content/docs/<locale>/**/meta.json), merged over META per folder.\n" +
    `export const META_LOCALES = ${JSON.stringify(metaLocales)} as const;\n`;
  // Write only when changed — `kura dev` re-runs index on restart, and an unconditional write would
  // bump the mtime every time, which the dev watcher sees as an edit → infinite restart loop.
  if (!fs.existsSync(metaTs) || fs.readFileSync(metaTs, "utf8") !== metaContents) {
    fs.writeFileSync(metaTs, metaContents);
  }
  const metaCount = Object.keys(meta).length + Object.values(metaLocales).reduce((n, m) => n + Object.keys(m).length, 0);
  if (metaCount) console.log(`kura index: validated ${metaCount} meta.json file(s)`);

  type Entry = Parameters<typeof buildIndex>[0]["entries"][number];
  const mod = (await import(pathToFileURL(contentPath).href)) as {
    DOCS?: Entry[];
    docs?: (locale?: string) => Entry[];
  };
  const DOCS = mod.DOCS ?? [];
  if (!DOCS.length) {
    console.error("kura index: no docs found in app/_content.ts");
    process.exit(1);
  }

  // Discover locales from content/<col>/<locale>/ subdirs (and each configured source's own
  // locale mirrors), then collect each locale's actual variants (entry.locale === locale;
  // fallbacks stay in the default set). Both the search index and the MDX precompile cover
  // default + every variant → cross-lingual by construction.
  const locales = mod.docs ? discoverLocales(cwd, contentSources, declaredLocales) : new Set<string>();
  const variants: Entry[] = [];
  for (const locale of locales) for (const e of mod.docs!(locale)) if (e.locale === locale) variants.push(e);
  const allEntries = [...DOCS, ...variants];

  // Optional "Last updated on …" dates (config.lastUpdated, read via loadCliConfig — never executes
  // user config). Default OFF. We ALWAYS write app/_dates.ts (empty when off) so the
  // generated _kura.ts imports it unconditionally — same reason --no-embed writes a stub, not a
  // delete. Frozen before the up-to-date short-circuit so the file always exists.
  const datesTs = path.join(cwd, "app", "_dates.ts");
  const lastUpdatedOn = cfg.lastUpdated;
  const lastUpdated: Record<string, string> = lastUpdatedOn ? collectLastUpdated(cwd, contentSources, declaredLocales) : {};
  if (lastUpdatedOn) {
    const missing = DOCS.filter((d) => !(d.slug in lastUpdated)).map((d) => d.slug);
    console.log(`kura index: lastUpdated — ${Object.keys(lastUpdated).length} git date(s), ${DOCS.length - missing.length}/${DOCS.length} docs covered`);
    if (missing.length) {
      console.warn(`kura index: lastUpdated — no git date for ${missing.length} doc(s) (${missing.slice(0, 4).join(", ")}${missing.length > 4 ? "…" : ""}). Uncommitted, or a shallow CI clone — set checkout fetch-depth: 0.`);
    }
  }

  // Frozen link-resolution data (app/_links.ts) — ALWAYS written, like _dates.ts, so the generated
  // _kura.ts can import it unconditionally. Source paths let each page resolve authored links from
  // its own file; the repo oracle is corpus-filtered (only targets links actually reach).
  {
    const repoRoot = repoRootOf(cwd);
    const toRepoPath = repoPathMapper(cwd, repoRoot, sourceMapOf());
    const { sourcePaths, localeSourcePaths } = collectSourcePaths(cwd, contentSources, declaredLocales, toRepoPath);
    // The remote lookup runs where the repo actually is — the checkout root when the build tree
    // is a copy (KURA_REPO_ROOT), else the project cwd.
    const { url: repoUrl, reason } = detectRepo(cfg.repo, process.env, () => gitOriginUrl(repoRoot ?? cwd));
    let repoFiles: string[] = [];
    let repoDirs: string[] = [];
    let oracleNote = "";
    if (repoUrl && repoRoot) {
      const tracked = gitTrackedFiles(repoRoot);
      if (tracked) {
        const fromOf = (e: Entry): string | undefined =>
          (e.locale ? localeSourcePaths[e.locale]?.[e.slug] : undefined) ?? sourcePaths[e.slug];
        const targets = collectRepoTargets(allEntries.map((e) => ({ original: e.original, fromPath: fromOf(e) })), tracked);
        repoFiles = targets.repoFiles;
        repoDirs = targets.repoDirs;
        oracleNote = `, ${repoFiles.length + repoDirs.length} repo target(s)`;
      } else oracleNote = ", repo oracle off (git ls-files failed)";
    }
    writeIfChanged(path.join(cwd, "app", "_links.ts"),
      renderLinksTs({ repoUrl, ref: linkRef(), sourcePaths, localeSourcePaths, repoFiles, repoDirs }));
    const covered = DOCS.filter((d) => d.slug in sourcePaths).length;
    console.log(`kura index: links — repo=${repoUrl ?? `none (${reason})`}, sourcePaths cover ${covered}/${DOCS.length} docs${oracleNote}`);
    if (covered < DOCS.length) {
      const missing = DOCS.filter((d) => !(d.slug in sourcePaths)).map((d) => d.slug);
      console.warn(`kura index: links — no repo path for ${missing.length} doc(s) (${missing.slice(0, 4).join(", ")}${missing.length > 4 ? "…" : ""}); their links use legacy matching only. Outside the git repo? Set KURA_REPO_ROOT / KURA_SOURCE_MAP.`);
    }
  }
  // Sort keys so the frozen output is deterministic regardless of readdir order (stable writeIfChanged).
  const datesSorted = Object.fromEntries(Object.entries(lastUpdated).sort(([a], [b]) => a.localeCompare(b)));
  writeIfChanged(datesTs,
    "// AUTO-GENERATED by `kura index` — per-doc last-updated dates (git commit date, ISO). Empty unless\n" +
    "// kura.config.ts sets `lastUpdated: true`.\n" +
    `export const LAST_UPDATED: Record<string, string> = ${JSON.stringify(datesSorted)};\n`,
  );

  // --no-embed: skip the search index entirely (build MDX only). Use it when the site runs
  // WITHOUT a runtime embedder — search degrades to a lexical scan, so no model/index is needed
  // (e.g. a Cloudflare Workers deploy without Workers AI).
  const noEmbed = process.argv.includes("--no-embed");

  // Content format: kura.config.ts `markdown` (default "mdx"), overridable per run with --commonmark.
  // "commonmark" renders via MDX format:'md' — no MDX/JSX parsing, so a literal {…} can't be read as
  // a JS expression and drop the page. Resolved BEFORE the hash so a format switch forces a rebuild
  // (otherwise the same content short-circuits and leaves _mdx.ts in the previous format).
  const commonmark = process.argv.includes("--commonmark") || cfg.commonmark;
  const format = commonmark ? "md" : "mdx";
  const strict = process.argv.includes("--strict");
  // Extra shiki grammar names from `highlight.langs` — merged onto @kurajs/docs's curated base list
  // so projects can highlight DSL fences the defaults miss (e.g. "hcl", "dockerfile").
  const highlightLangs = cfg.highlightLangs;

  // Content hash — skip rebuilds when nothing changed, so `kura index` is cheap to run before
  // every dev/build. Covers the mode + format + model + locale/slug/body of every entry.
  const hashInput = JSON.stringify([model, noEmbed, format, highlightLangs, contentSources, [...declaredLocales].sort(), allEntries.map((e) => [e.locale ?? "", e.slug, e.body])]);
  const contentHash = crypto.createHash("sha256").update(hashInput).digest("hex").slice(0, 16);
  const stamp = `// content-hash: ${contentHash}\n`;
  const hashOf = (f: string) => (fs.existsSync(f) ? fs.readFileSync(f, "utf8").match(/content-hash: (\S+)/)?.[1] : undefined);
  // --strict must re-check failures every run, so it never short-circuits — a cached _mdx.ts from a
  // prior non-strict run could otherwise hide failures and let `kura build --strict` pass wrongly.
  // --no-embed also requires app/_index.ts to actually export INDEX_B64 — not merely exist: a missing,
  // corrupt, or hand-edited stub would otherwise short-circuit and leave a broken `import { INDEX_B64 }`
  // in the config. (The embed path is already covered by its content-hash stamp.)
  const exportsIndexB64 = (f: string) =>
    fs.existsSync(f) && /export\s+const\s+INDEX_B64\b/.test(fs.readFileSync(f, "utf8"));
  const upToDate = !strict && (noEmbed
    ? hashOf(mdxTs) === contentHash && exportsIndexB64(indexTs)
    : hashOf(indexTs) === contentHash && fs.existsSync(mdxTs));
  if (upToDate) {
    console.log(`kura index: up to date (${allEntries.length} docs, hash ${contentHash}) — skipped`);
    return;
  }
  fs.mkdirSync(path.dirname(mdxTs), { recursive: true });

  if (!noEmbed) {
    const localeTag = locales.size ? ` (+${variants.length} variants across ${locales.size} locales)` : "";
    console.log(`kura index: embedding ${DOCS.length} docs${localeTag} (model ${model})…`);
    const t0 = Date.now();
    // Lazy import: only the embed path needs the ML stack, so --no-embed sites never load it
    // (and never install @kurajs/transformers — it's an optional peer).
    const { transformers } = await import("@kurajs/transformers").catch(() => {
      console.error("kura index: embedding needs @kurajs/transformers — install it, or use --no-embed.");
      return process.exit(1);
    });
    const bytes = await buildIndex({ entries: allEntries, embedder: transformers({ model }) });
    const b64 = Buffer.from(bytes).toString("base64");
    fs.writeFileSync(
      indexTs,
      stamp +
        "// AUTO-GENERATED by `kura index` — do not edit. Frozen search index (base64) so the worker\n" +
        "// bundle imports it instead of reading the filesystem (Workers-safe).\n" +
        `export const INDEX_B64 = ${JSON.stringify(b64)};\n`,
    );
    console.log(`kura index: wrote app/_index.ts (${(bytes.length / 1024).toFixed(0)}KB index) in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
  } else {
    // --no-embed: skip the build-time vector index, but write an empty STUB rather than deleting it,
    // so a semantic-search app's `import { INDEX_B64 } from "./app/_index"` still resolves (deleting it
    // broke the build). The config decodes "" → no index, so the runtime searches by keyword, or
    // builds the index lazily on first query if an embedder is configured. Unstamped (no content-hash
    // line) so dropping --no-embed regenerates the real index next time.
    writeIfChanged(indexTs, "// AUTO-GENERATED by `kura index --no-embed` — empty search-index stub.\nexport const INDEX_B64 = \"\";\n");
    console.log("kura index: --no-embed — MDX only, empty search-index stub (runtime: keyword, or lazy embed if an embedder is set)");
  }

  // Precompile MDX -> static HTML with curated components (build-time; Workers-safe at runtime).
  // Bucketed by locale: "default" for the flat (default-locale) files, plus one per variant locale.
  // renderMdxBuckets collects per-page failures instead of throwing (the silent-drop guard lives in
  // @kurajs/docs so it's unit-tested there).
  const { renderMdxBuckets } = await import("@kurajs/docs/mdx");
  const byLocale = new Map<string, Entry[]>();
  for (const e of variants) byLocale.set(e.locale!, [...(byLocale.get(e.locale!) ?? []), e]);
  const { map, failures } = await renderMdxBuckets([
    { bucket: "default", entries: DOCS },
    ...[...byLocale].map(([bucket, entries]) => ({ bucket, entries })),
  ], undefined, format, highlightLangs);
  fs.writeFileSync(
    mdxTs,
    stamp +
      "// AUTO-GENERATED by `kura index` — do not edit. Frozen precompiled MDX (locale → slug → html).\n" +
      `export const MDX: Record<string, Record<string, string>> = ${JSON.stringify(map)};\n`,
  );
  // LOUD per-page failures: a page that fails MDX is silently dropped to plain-markdown html, so the
  // author never learns it broke unless we say so. Print slug + the first error line — NEVER swallow.
  for (const f of failures) {
    // In commonmark mode the "set markdown: commonmark" hint is already in effect — drop it and just
    // name the renderer that failed (a commonmark failure is a genuine parse error, not the {…} footgun).
    const hint = commonmark ? "" : `; wrap any literal {…}/<…> in backticks, or set markdown: "commonmark"`;
    console.error(`kura index: ⚠ ${commonmark ? "CommonMark" : "MDX"} failed for "${f.slug}"${f.bucket !== "default" ? ` [${f.bucket}]` : ""} — ${f.error.split("\n")[0]} (renders as plain markdown${hint})`);
  }
  // Count ATTEMPTS (not map size): a dropped page isn't in the map, so map size == ok and the ratio
  // would always read N/N — hiding the fallbacks and disagreeing with the "(N docs)" up-to-date line.
  const total = DOCS.length + variants.length;
  const ok = total - failures.length;
  const tag = locales.size ? ` across ${locales.size + 1} locales` : "";
  console.log(`kura index: rendered ${ok}/${total} docs via ${commonmark ? "CommonMark" : "MDX"}${tag} -> app/_mdx.ts` + (failures.length ? ` (${failures.length} fell back — see warnings above)` : ""));
  // --strict: a silently-dropped page is a content bug. Fail the build instead of shipping the
  // plain-markdown fallback, so CI catches it (the author never finds out otherwise).
  if (failures.length && strict) {
    console.error(`kura index: --strict — ${failures.length} page(s) failed to render; failing the build.`);
    process.exit(1);
  }
}

// One Kura surface over June: dev / build / deploy each freeze content (june gen) + the search
// index/MDX (kura index), then hand off to the `june` bin — which loads its own TS source and
// owns the dev watch supervisor. Users only ever type `kura`.
const flag = (name: string): boolean => process.argv.includes(`--${name}`);

// Forward extra args to june, dropping the kura-only flags (--no-embed, --model <v>, --strict,
// --commonmark) — june wouldn't understand them.
function passthrough(): string[] {
  const out: string[] = [];
  const a = process.argv.slice(3);
  for (let i = 0; i < a.length; i++) {
    if (a[i] === "--no-embed") continue;
    if (a[i] === "--strict" || a[i] === "--commonmark") continue; // kura index-only
    if (a[i] === "--model") { i++; continue; }
    out.push(a[i]!);
  }
  return out;
}

// Find a bin shim, walking up so it works both in a standalone app (local node_modules) and a
// workspace member (the bin is hoisted to the root node_modules/.bin).
function findBin(cwd: string, bin: string): string | null {
  const name = process.platform === "win32" ? `${bin}.cmd` : bin;
  let dir = cwd;
  for (;;) {
    const p = path.join(dir, "node_modules", ".bin", name);
    if (fs.existsSync(p)) return p;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}
// Second search root: this CLI module's own directory. Under Bun's isolated linker the transitive
// `june` bin isn't hoisted to the app root — it lives in @kurajs/cli's own node_modules/.bin — so
// also walk up from here. (Under the hoisted linker / npm, the cwd walk above already finds it.)
const SELF_DIR = path.dirname(fileURLToPath(import.meta.url));
const findJuneBin = (cwd: string) => findBin(cwd, "june") ?? findBin(SELF_DIR, "june");

// Run the app's `june` bin (it handles TS loading + the dev watcher); resolve with its exit code.
function runJune(cwd: string, args: string[]): Promise<number> {
  const bin = findJuneBin(cwd);
  if (!bin) {
    console.error("kura: couldn't find the June runtime — try reinstalling @kurajs/cli.");
    return Promise.resolve(1);
  }
  return new Promise((resolve) => {
    const child = spawn(bin, args, { stdio: "inherit" });
    child.on("error", (e) => {
      console.error(`kura: couldn't run june (${e.message}).`);
      resolve(1);
    });
    child.on("exit", (code) => resolve(code ?? 0));
  });
}

// Run `wrangler` from the built worker dir (dist/) — used by `kura preview` to serve the freshly
// built Worker locally, a production-faithful preview.
function runWrangler(distDir: string, args: string[]): Promise<number> {
  const bin = findBin(distDir, "wrangler");
  if (!bin) {
    console.error("kura preview: couldn't find wrangler — install it with `npm i -D wrangler`.");
    return Promise.resolve(1);
  }
  return new Promise((resolve) => {
    const child = spawn(bin, args, { stdio: "inherit", cwd: distDir });
    child.on("error", (e) => { console.error(`kura preview: couldn't run wrangler (${e.message}).`); resolve(1); });
    child.on("exit", (code) => resolve(code ?? 0));
  });
}

// Run `kura index` in a SHORT-LIVED child so the embedder's native runtime (onnxruntime) is
// loaded and torn down in its own process — keeping the long-running dev/build/deploy parent
// ML-free (and dodging ORT's noisy teardown on some platforms).
function runKuraIndex(cwd: string): Promise<number> {
  const args = [process.argv[1]!, "index"];
  if (flag("no-embed")) args.push("--no-embed");
  if (flag("strict")) args.push("--strict"); // forward to the index child so `kura build --strict` works
  if (flag("commonmark")) args.push("--commonmark");
  const model = arg("model");
  if (model) args.push("--model", model);
  return new Promise((resolve) => {
    const child = spawn(process.execPath, args, { stdio: "inherit", cwd });
    child.on("error", (e) => { console.error(`kura: index failed (${e.message}).`); resolve(1); });
    child.on("exit", (code) => resolve(code ?? 0));
  });
}

// Write `content` to `filePath` only when it differs (idempotent, avoids
// mtime bumps that would trigger unnecessary dev-server restarts).
function writeIfChanged(filePath: string, content: string): void {
  if (!fs.existsSync(filePath) || fs.readFileSync(filePath, "utf8") !== content) {
    fs.writeFileSync(filePath, content);
  }
}

// Generate all kura framework files into .june/ so the user never manages boilerplate.
// Lives in .june/ (June's own artifact dir, already gitignored):
//   .june/config.ts       — June site/deploy/agent config (via kuraJuneConfig)
//   .june/routes/_kura.ts — createDocs() barrel (not a route, used by routes below)
//   .june/routes/layout.tsx           — persistent docs shell (segment boundary)
//   .june/routes/page.tsx              — home route
//   .june/routes/<basePath>/[[...slug]]/page.tsx — docs route (default <basePath> = docs; "" mounts
//                                        the catch-all directly under routes/, served at site root)
//   .june/routes/search/page.tsx       — search route (always /search, basePath-independent)
//   .june/routes/og/[[...slug]]/route.ts — OG image route (catch-all: nested slugs resolve)
//   .june/routes/_client.ts            — island client entry (⌘K search)
// Convention-over-configuration defaults for a kura.toml project: a project commits only kura.toml
// (+ its docs/), so the CLI fills in the boilerplate create-kura would otherwise scaffold — but only
// when absent (the app can override any of them). Skipped for kura.config.ts projects, which
// create-kura already scaffolds. `import` deps (@kurajs/docs, react) still come from package.json —
// those must be installed, so the wrapping action/create-kura provides that one file.
function ensureBoilerplate(cwd: string, cfg: import("./config-load.js").CliConfig): void {
  if (cfg.source !== "toml") return;
  const writeIfAbsent = (rel: string, content: string): void => {
    const p = path.join(cwd, rel);
    if (fs.existsSync(p)) return;
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  };
  writeIfAbsent("app/global.css", '@import "tailwindcss";\n@import "@kurajs/docs/css";\n');
  writeIfAbsent("tsconfig.json", JSON.stringify({ extends: "@kurajs/docs/tsconfig.kura.json", include: ["app"] }, null, 2) + "\n");
  // A landing page: the site homepage AND a seed for the content collection so `june gen` bootstraps
  // a mount-only site. Title/description come from [site]; the H1 drives the on-page heading.
  const name = cfg.siteName ?? "Documentation";
  const desc = cfg.siteDescription ?? "";
  writeIfAbsent("content/docs/index.md",
    `---\ntitle: ${JSON.stringify(name)}\n${desc ? `description: ${JSON.stringify(desc)}\n` : ""}---\n\n# ${name}\n\n` +
    `${desc ? desc + "\n\n" : ""}Use the sidebar or search (\`/\`) to browse the docs. Every page is also available as ` +
    "Markdown (append `.md`) and JSON, and via an MCP tool at `/mcp`.\n");
}

// June v0.0.44+ scans .june/routes/ alongside app/; app/ takes priority (override slot).
function generateJuneConfig(cwd: string): void {
  const cfg = loadCliConfig(cwd);
  if (cfg.source === "none") return; // no kura.toml / kura.config.ts → not a kura app, skip
  const toml = cfg.source === "toml";

  ensureBoilerplate(cwd, cfg); // default app/global.css + tsconfig + a landing page (toml projects)

  const juneDir = path.join(cwd, ".june");
  const routesDir = path.join(juneDir, "routes");
  // The config import lines + the `kuraConfig` binding for a shim. `ref` is the shim-relative path to
  // the config module: the materialized ./kura.gen for toml, or the user's kura.config.ts.
  const cfgImports = (ref: string, docsToo: boolean): string => {
    const named = docsToo ? "createDocs" : "kuraJuneConfig";
    return toml
      ? `import { ${named}, fromKuraToml } from "@kurajs/docs";\nimport __toml from "${ref}";\nconst kuraConfig = fromKuraToml(__toml);\n`
      : `import { ${named} } from "@kurajs/docs";\nimport kuraConfig from "${ref}";\n`;
  };
  // config.ts is in .june/ ; _kura.ts is in .june/routes/ — kura.gen.ts sits in .june/.
  const configRef = { config: toml ? "./kura.gen" : "../kura.config.ts", kura: toml ? "../kura.gen" : "../../kura.config.ts" };
  const cfgFile = toml ? "kura.toml" : "kura.config.ts";
  const staticTarget = cfg.staticTarget; // no server → drop the dynamic OG route + og:image tags
  // basePath drives the docs route location (June has no route-prefix config — URL = disk).
  const { docsDir, kuraImport } = docsRoute(routesDir, cfg.basePathSegments);
  // Catch-all so nested doc slugs (/og/getting-started/sdk.png) resolve, not just /og/sdk.png.
  const ogDir = path.join(routesDir, "og", "[[...slug]]");
  const searchDir = path.join(routesDir, "search");
  pruneStaleDocsRoutes(routesDir, docsDir); // drop a docs route a prior basePath left behind
  // Drop ONLY the old single-segment og/[slug] from a prior version (a leftover [slug] would win for
  // single-segment OG URLs). Targeted, not a wholesale rm of routes/og, so writeIfChanged keeps the
  // og/[[...slug]] route's mtime stable across runs.
  fs.rmSync(path.join(routesDir, "og", "[slug]"), { recursive: true, force: true });
  // Static: prune the whole OG route dir (a prior non-static run may have written it).
  if (staticTarget) fs.rmSync(path.join(routesDir, "og"), { recursive: true, force: true });
  for (const d of [juneDir, routesDir, docsDir, searchDir, ...(staticTarget ? [] : [ogDir])]) {
    fs.mkdirSync(d, { recursive: true });
  }

  // A kura.toml is parsed by the CLI (smol-toml — no runtime .toml import, so June can run under node
  // or bun) and MATERIALIZED here; the shims import this plain module and normalize it with
  // fromKuraToml() at load time. (kura.config.ts projects skip this — their shims import it directly.)
  if (toml) {
    writeIfChanged(path.join(juneDir, "kura.gen.ts"),
      "// @kura-generated from kura.toml — do not edit. Regenerated on every build.\n" +
      `export default ${JSON.stringify(cfg.raw)} as const;\n`);
  }

  const HEADER = `// @kura-generated — do not edit. Configure your site in ${cfgFile} instead.\n`;

  // .june/config.ts
  writeIfChanged(path.join(juneDir, "config.ts"),
    HEADER +
    cfgImports(configRef.config, false) +
    'import { DOCS } from "../app/_content";\n' +
    "\nexport default kuraJuneConfig(kuraConfig, { DOCS });\n",
  );

  // .june/routes/_kura.ts — createDocs() singleton; imported by every route below.
  writeIfChanged(path.join(routesDir, "_kura.ts"),
    HEADER +
    cfgImports(configRef.kura, true) +
    'import { DOCS, doc, docs } from "../../app/_content";\n' +
    'import { MDX } from "../../app/_mdx";\n' +
    'import { META, META_LOCALES } from "../../app/_meta";\n' +
    'import { LAST_UPDATED } from "../../app/_dates";\n' +
    'import { LINKS } from "../../app/_links";\n' +
    "\nexport const kura = createDocs({\n" +
    "  content: { DOCS, doc, docs },\n" +
    "  mdxHtml: MDX,\n" +
    "  meta: META,\n" +
    "  metaLocales: META_LOCALES,\n" +
    "  lastUpdated: LAST_UPDATED,\n" +
    "  links: LINKS,\n" +
    "  config: kuraConfig,\n" +
    "});\n",
  );

  // .june/routes/layout.tsx — the PERSISTENT docs shell (segment boundary). Soft navigation morphs
  // only the <JuneOutlet> content inside it, so the sidebar (and its open folders) never re-render.
  writeIfChanged(path.join(routesDir, "layout.tsx"),
    HEADER +
    'import { kura } from "./_kura";\n' +
    "export const segmentBoundary = true;\n" +
    "export default kura.layout;\n",
  );

  // .june/routes/page.tsx — home
  writeIfChanged(path.join(routesDir, "page.tsx"),
    HEADER +
    'import { kura } from "./_kura";\n' +
    "export const loader = kura.home.loader;\n" +
    "export const md = kura.home.md;\n" +
    "export const json = kura.home.json;\n" +
    "export const metadata = kura.home.metadata;\n" +
    "export default kura.home.View;\n",
  );

  // .june/routes/<basePath>/[[...slug]]/page.tsx — docs (import depth follows basePath, see above)
  writeIfChanged(path.join(docsDir, "page.tsx"),
    HEADER +
    `import { kura } from "${kuraImport}";\n` +
    "export const loader = kura.docRoute.loader;\n" +
    "export const md = kura.docRoute.md;\n" +
    "export const json = kura.docRoute.json;\n" +
    "export const metadata = kura.docRoute.metadata;\n" +
    // staticPaths enumerates every doc page (× locale) so the static() target prerenders this
    // dynamic catch-all to files. Inert on server targets (June only reads it when building static).
    "export const staticPaths = kura.docRoute.staticPaths;\n" +
    "export default kura.docRoute.View;\n",
  );

  // .june/routes/search/page.tsx — search
  writeIfChanged(path.join(searchDir, "page.tsx"),
    HEADER +
    'import { kura } from "../_kura";\n' +
    "export const loader = kura.searchRoute.loader;\n" +
    "export const json = kura.searchRoute.json;\n" +
    "export const metadata = kura.searchRoute.metadata;\n" +
    "export default kura.searchRoute.View;\n",
  );

  // .june/routes/og/[[...slug]]/route.ts — OG image (catch-all → nested slugs resolve).
  // Omitted on a static target (no server to render images; og:image tags are dropped too).
  if (!staticTarget) {
    writeIfChanged(path.join(ogDir, "route.ts"),
      HEADER +
      'import { kura } from "../../_kura";\n' +
      "export default kura.ogRoute;\n",
    );
  }

  // .june/routes/_client.ts — island client entry. startJuneClient wires island hydration AND the
  // morph router (when clientRouter is on) — without it the router never starts. initSearch then
  // lights up the ⌘K palette. (Calling only initSearch silently disables the router + islands.)
  writeIfChanged(path.join(routesDir, "_client.ts"),
    HEADER +
    'import { startJuneClient } from "@junejs/core/islands-client";\n' +
    'import { initSearch } from "@kurajs/docs/client";\n' +
    'import { ISLAND_LOADERS } from "../../app/_islands.gen";\n' +
    "\nstartJuneClient({ loaders: ISLAND_LOADERS });\n" +
    "initSearch();\n",
  );
}

async function freeze(cwd: string): Promise<void> {
  generateJuneConfig(cwd); // write .june shims from kura.toml / kura.config.ts
  let code = await runJune(cwd, ["gen"]); // june gen → app/_content.ts
  if (code) process.exit(code);
  code = await runKuraIndex(cwd); // kura index → app/_index.ts + _mdx.ts (own process)
  if (code) process.exit(code);
}

const cmd = process.argv[2];
const cwd = process.cwd();
switch (cmd) {
  case "index":
    await cmdIndex();
    break;
  case "dev":
    await freeze(cwd);
    process.exit(await runJune(cwd, ["dev", ...passthrough()]));
    break;
  case "build":
    await freeze(cwd);
    process.exit(await runJune(cwd, ["build", ...passthrough()]));
    break;
  case "preview": {
    // Build the Worker, then serve it locally with wrangler — a production-faithful preview.
    await freeze(cwd);
    const code = await runJune(cwd, ["build", ...passthrough()]);
    if (code) process.exit(code);
    process.exit(await runWrangler(path.join(cwd, "dist"), ["dev", "worker.js", "--config", "wrangler.jsonc", ...passthrough()]));
    break;
  }
  case "deploy": {
    await freeze(cwd);
    const dargs = ["deploy"];
    for (const f of ["dry-run", "prod", "skip-migrate", "allow-destructive"]) if (flag(f)) dargs.push(`--${f}`);
    process.exit(await runJune(cwd, dargs));
    break;
  }
  default:
    console.log(
      "Kura CLI\n" +
        "  kura dev [--no-embed]       freeze content + index, then run the dev server\n" +
        "  kura build [--no-embed]     freeze + build the Worker bundle\n" +
        "  kura preview [--no-embed]   build, then serve the Worker locally via wrangler\n" +
        "  kura deploy [--no-embed]    freeze + deploy to Cloudflare ([--dry-run] [--prod])\n" +
        "  kura index [--no-embed] [--model <hf-model>]   (re)build the search index + MDX only",
    );
    process.exit(cmd ? 1 : 0);
}
