#!/usr/bin/env node
// Kura CLI.
//   kura index [--model Xenova/bge-m3]
//     Build the search index + precompiled MDX for the current Kura docs app and FREEZE both
//     as importable modules (app/_index.ts, app/_mdx.ts) — so the worker bundle imports them
//     and never reads the filesystem (Workers-safe; mirrors June's app/_content.ts freeze).
//     A content hash short-circuits re-embedding when nothing changed (cheap to run pre-dev).
import { buildIndex } from "@kurajs/docs/search";
import { transformers } from "@kurajs/transformers";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { pathToFileURL } from "node:url";

function arg(name: string, def?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
}

async function cmdIndex(): Promise<void> {
  const cwd = process.cwd();
  const contentPath = path.join(cwd, "app", "_content.ts");
  if (!fs.existsSync(contentPath)) {
    console.error("kura index: app/_content.ts not found — run `june gen` first (in a Kura docs app).");
    process.exit(1);
  }
  const model = arg("model", "Xenova/bge-m3")!;
  const indexTs = path.join(cwd, "app", "_index.ts");
  const mdxTs = path.join(cwd, "app", "_mdx.ts");

  type Entry = Parameters<typeof buildIndex>[0]["entries"][number];
  const mod = (await import(pathToFileURL(contentPath).href)) as {
    DOCS?: Entry[];
    docs?: (locale?: string) => Entry[];
  };
  const DOCS = mod.DOCS ?? [];
  if (!DOCS.length) {
    console.error("kura index: no docs found in app/_content.ts");
    process.exit(1);
  }

  // Discover locales from content/<col>/<locale>/ subdirs, then collect each locale's actual
  // variants (entry.locale === locale; fallbacks stay in the default set). Both the search
  // index and the MDX precompile cover default + every variant → cross-lingual by construction.
  const LOCALE_DIR = /^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$/;
  const contentRoot = path.join(cwd, "content");
  const locales = new Set<string>();
  if (mod.docs && fs.existsSync(contentRoot)) {
    for (const col of fs.readdirSync(contentRoot, { withFileTypes: true })) {
      if (!col.isDirectory()) continue;
      for (const sub of fs.readdirSync(path.join(contentRoot, col.name), { withFileTypes: true })) {
        if (sub.isDirectory() && LOCALE_DIR.test(sub.name)) locales.add(sub.name);
      }
    }
  }
  const variants: Entry[] = [];
  for (const locale of locales) for (const e of mod.docs!(locale)) if (e.locale === locale) variants.push(e);
  const allEntries = [...DOCS, ...variants];

  // --no-embed: skip the search index entirely (build MDX only). Use it when the site runs
  // WITHOUT a runtime embedder — search degrades to a lexical scan, so no model/index is needed
  // (e.g. a Cloudflare Workers deploy without Workers AI).
  const noEmbed = process.argv.includes("--no-embed");

  // Content hash — skip rebuilds when nothing changed, so `kura index` is cheap to run before
  // every dev/build. Covers the mode + model + locale/slug/body of every entry.
  const hashInput = JSON.stringify([model, noEmbed, allEntries.map((e) => [e.locale ?? "", e.slug, e.body])]);
  const contentHash = crypto.createHash("sha256").update(hashInput).digest("hex").slice(0, 16);
  const stamp = `// content-hash: ${contentHash}\n`;
  const hashOf = (f: string) => (fs.existsSync(f) ? fs.readFileSync(f, "utf8").match(/content-hash: (\S+)/)?.[1] : undefined);
  const upToDate = noEmbed ? hashOf(mdxTs) === contentHash : hashOf(indexTs) === contentHash && fs.existsSync(mdxTs);
  if (upToDate) {
    console.log(`kura index: up to date (${allEntries.length} docs, hash ${contentHash}) — skipped`);
    return;
  }
  fs.mkdirSync(path.dirname(mdxTs), { recursive: true });

  if (!noEmbed) {
    const localeTag = locales.size ? ` (+${variants.length} variants across ${locales.size} locales)` : "";
    console.log(`kura index: embedding ${DOCS.length} docs${localeTag} (model ${model})…`);
    const t0 = Date.now();
    const bytes = await buildIndex({ entries: allEntries, embedder: transformers({ model }) });
    const b64 = Buffer.from(bytes).toString("base64");
    fs.writeFileSync(
      indexTs,
      stamp +
        "// AUTO-GENERATED by `kura index` — do not edit. Frozen search index (base64) so the worker\n" +
        "// bundle imports it instead of reading the filesystem (Workers-safe).\n" +
        `export const INDEX_B64 = ${JSON.stringify(b64)};\n`,
    );
    console.log(`kura index: wrote app/_index.ts (${(bytes.length / 1024).toFixed(0)}KB index) in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
  } else {
    if (fs.existsSync(indexTs)) fs.rmSync(indexTs);
    console.log("kura index: --no-embed — MDX only, no search index (runtime search is lexical)");
  }

  // Precompile MDX -> static HTML with curated components (build-time; Workers-safe at runtime).
  // Bucketed by locale: "default" for the flat (default-locale) files, plus one per variant locale.
  const { mdxToHtml } = await import("@kurajs/docs/mdx");
  const map: Record<string, Record<string, string>> = { default: {} };
  let ok = 0;
  const render = async (bucket: string, e: Entry) => {
    try {
      (map[bucket] ??= {})[e.slug] = await mdxToHtml(e.body);
      ok++;
    } catch {
      /* leave out → the app falls back to the plain markdown html */
    }
  };
  for (const d of DOCS) await render("default", d);
  for (const e of variants) await render(e.locale!, e);
  fs.writeFileSync(
    mdxTs,
    stamp +
      "// AUTO-GENERATED by `kura index` — do not edit. Frozen precompiled MDX (locale → slug → html).\n" +
      `export const MDX: Record<string, Record<string, string>> = ${JSON.stringify(map)};\n`,
  );
  const total = Object.values(map).reduce((n, b) => n + Object.keys(b).length, 0);
  const tag = locales.size ? ` across ${locales.size + 1} locales` : "";
  console.log(`kura index: rendered ${ok}/${total} docs via MDX${tag} -> app/_mdx.ts`);
}

const cmd = process.argv[2];
if (cmd === "index") {
  await cmdIndex();
} else {
  console.log(
    "Kura CLI\n" +
      "  kura index [--model <hf-model>]   build & freeze the docs search index + MDX\n" +
      "  kura index --no-embed             MDX only, no search index (runtime search is lexical)",
  );
  process.exit(cmd ? 1 : 0);
}
